name: auto-merge
on:
  pull_request:
permissions: write-all
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          merge-method:	squash